In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes

In [45]:
class SelfMLR:

    def __init__(self):
        self.coef = None
        self.intercept = None

    def fit(self, x_train, y_train):

        x_train = np.insert(x_train, 0, 1,axis =1)
        
        betas = np.linalg.inv(np.dot(x_train.T, x_train)).dot(x_train.T).dot(y_train)
        self.intercept = betas[0]
        self.coef = betas[1:]

    def predict(self, x_test):
        return (np.dot(x_test, self.coef) + self.intercept)

    def coef_(self):
        print(self.coef)

    def intercept_(self):
        print(self.intercept)

In [46]:
X,y = load_diabetes(return_X_y=True)

In [47]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [48]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [50]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [51]:
lr = SelfMLR()

In [52]:
lr.fit(X_train, y_train)

In [53]:
lr.coef_()

[  33.40954056 -292.24112825  481.08002807  369.05716136 -966.32463944
  589.771093    232.59825938  288.32164654  802.69901575   37.81345763]


In [54]:
lr.intercept_()

151.14665446569643


In [55]:
y_pred = lr.predict(X_test)

In [56]:
y_pred

array([ 74.43280315,  93.01188422, 174.89583708,  52.70477804,
       180.6344672 , 145.29489212, 112.87543999, 121.31739633,
        86.80055781,  72.09487051, 106.45282573, 193.85987207,
       182.28344544, 125.44811935, 155.8896893 , 139.16031299,
       176.97501885, 119.39134941, 110.71759865, 183.79817912,
       215.37006731, 181.15425179,  58.74452494, 228.82182365,
        54.20964003, 107.86930863, 157.15782778, 180.13351581,
        62.2029307 ,  67.18271285, 190.82019192, 118.09294588,
       260.8951241 , 183.19776479, 105.61124665, 175.91603519,
       176.89309477, 156.04689432, 146.92759805, 157.34037113,
       198.17713428, 168.03067448, 237.98412043,  71.34000677,
       237.44866784, 108.06983532, 152.11844679,  50.31084484,
       199.55707357, 139.53035368, 110.45552956, 101.51968242,
       154.91473627, 228.90111686,  54.52296474, 187.29195473,
       106.15268895,  93.61822132, 190.00645205, 226.39902673,
       124.54158588,  97.09381516, 168.71853743, 249.77